### ISSUE TITLE
Flow  io.cloudslang.vmware.vcenter.virtual_machines.get_virtual_machine_details does not retrieve IP address when VM just powered on

### ISSUE THREAD

**Issue by pe-pan** [CloudSlang/cs-content#1028]
I've got the following code.
```
namespace: io.cloudslang.demo
imports:
  base: io.cloudslang.base
  vm: io.cloudslang.vmware.vcenter.virtual_machines
flow:
  name: deploy_tomcat
  inputs:
    - hostname
    - username
    - password
    - image: "Ubuntu"
    - folder: "Students"
  workflow:
    - uuid_generator:
        do:
          base.utils.uuid_generator:
        publish:
          - uuid: '${new_uuid}'
        navigate:
          - SUCCESS: trim
    - trim:
          do:
            base.strings.substring:
              - origin_string: '${"petr-"+uuid}'
              - end_index: '13'
          publish:
            - id: '${new_string}'
          navigate:
            - FAILURE: FAILURE
            - SUCCESS: clone_vm
    - clone_vm:
        do:
          vm.clone_virtual_machine:
            - host: '${hostname}'
            - hostname: 'trnesxi3.eswdc.net'
            - clone_host: 'trnesxi3.eswdc.net'
            - clone_data_store: 'datastore2'
            - username: '${username}'
            - password: '${password}'
            - data_center_name: 'CAPA1 Datacenter'
            - is_template: 'false'
            - virtual_machine_name: '${image}'
            - clone_name: '${id}'
            - folder_name: '${folder}'
        navigate:
          - FAILURE: FAILURE
          - SUCCESS: power_on
    - power_on:
        do:
          vm.power_on_virtual_machine:
            - host: '${hostname}'
            - username: '${username}'
            - password: '${password}'
            - virtual_machine_name: '${id}'
        navigate:
          - FAILURE: FAILURE
          - SUCCESS: get_details
    - get_details:
        do:
          vm.get_virtual_machine_details:
            - host: '${hostname}'
            - username: '${username}'
            - password: '${password}'
            - hostname: 'trnesxi3.swsc.hpe.com'
            - virtual_machine_name: '${id}'
        publish:
            - details : '${return_result}'
        navigate:
          - FAILURE: FAILURE
          - SUCCESS: get_ip
    - get_ip:
        do:
          base.json.get_value:
            - json_input: '${details}'
            - json_path: 'ipAddress'
        publish:
            - ip: '${return_result}'
        navigate:
            - FAILURE: FAILURE
            - SUCCESS: SUCCESS
  results:
      - FAILURE
      - SUCCESS

```
The trouble is that the get_ip flow gets no value. To make it work, I need to put a sleep operation (for 10-30 seconds) in between power_on and get_details flows.
IMHO, the **get_virtual_machine_details** flow should return the IP or wait for it when not available yet.
