### ISSUE TITLE
Flow io.cloudslang.base.comparisons.equals does not accept an empty parameter

### ISSUE THREAD

**Issue by pe-pan** [CloudSlang/cs-content#1033]
I'm trying to execute this flow:

```
namespace: io.cloudslang.demo
flow:
  name: test
  workflow:
    - is_empty:
        do:
          io.cloudslang.base.comparisons.equals:
            - first: 'a'
            - second: ''
        navigate:
            - 'TRUE': SUCCESS
            - 'FALSE': FAILURE
  results:
      - FAILURE
      - SUCCESS
```

It fails on

**SEVERE: Command failed java.lang.RuntimeException: Failed compilation for file  test.sl ,Exception is : java.lang.IllegalArgumentException: Cannot compile flow 'io.cloudslang.demo.test'. Step 'is_empty' does not declare all the mandatory inputs of its reference. The following inputs of 'io.cloudslang.base.comparisons.equals' are not private, required and with no default value: second.**

How does one compare the argument with an empty string?
