### ISSUE TITLE
string_equals inputs should be required

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cs-content#914]
https://github.com/CloudSlang/cloud-slang-content/blob/master/content/io/cloudslang/base/strings/string_equals.sl

```
  inputs:
    - first_string:
         required: false
    - second_string:
         required: false
```

it means I can compare two strings without supplying two strings?
